docs: change README to explain the situation
tarides/dune-binary-distribution pull request #3
Opened 2024-07-31 13:54 UTC by maiste

Quick change in the README to reflect the new way of deploying and generating the executables.

2024-07-31 18:40 UTC, moyodiallo requested changes
Great, just some suggestions.

2024-07-31 18:52 UTC, moyodiallo requested changes
Great, just some suggestions.

2024-07-31 18:52 UTC, moyodiallo commented on README.md
> +The configuration is in [./sandworm/bin/config.ml](./sandworm/bin/config.ml) file. When running in the pipeline, the _Sandworm_ binary is generated before the execution. As a result, the path taken i
```suggestion
The configuration is in [sandworm/bin/config.ml](./sandworm/bin/config.ml) file. When running in the pipeline, the _sandworm_ binary is generated. Make sure the files artifacts and rclone.conf are in the current directory where _sandworm_ binary is executed.
```

2024-07-31 18:52 UTC, moyodiallo commented on README.md
> +Now your setup is ready, supposing you are in the [./sandworm](./sandworm) directory, you can simply run the program with:
```suggestion
Now your setup is ready, you can simply run the program with:
```

2024-07-31 18:52 UTC, moyodiallo commented on README.md
> +$ dune exec -- sandworm
```suggestion
$ cd sandworm
$ ls
artifacts rclone.conf
$ dune exec -- sandworm
```

2024-07-31 18:52 UTC, moyodiallo commented on README.md
> +$ dune build
```suggestion
$ cd sandworm
$ dune build
$ ls
artifacts rclone.conf
```

2024-08-01 08:34 UTC, maiste commented
@moyodiallo thanks for the review! I have updated the files using most of your suggestions.

2024-08-01 09:00 UTC, moyodiallo approved these changes

2024-08-01 10:06 UTC, merged